In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("country_level_data.csv")

In [5]:
codebook = pd.read_csv("country_level_codebook.csv")

In [6]:
codebook.head()

,regionID,iso3c,country_name,incomeID,measurement,units,year,source,comments
0,EAS,ASM,American Samoa,UMC,composition_food_organic_waste_percent,%,2011.0,SPREP (Secretariat of the Pacific Regional Env...,NaN
1,EAS,ASM,American Samoa,UMC,composition_glass_percent,%,2011.0,SPREP (Secretariat of the Pacific Regional Env...,NaN
2,EAS,ASM,American Samoa,UMC,composition_metal_percent,%,2011.0,SPREP (Secretariat of the Pacific Regional Env...,NaN
3,EAS,ASM,American Samoa,UMC,composition_other_percent,%,2011.0,SPREP (Secretariat of the Pacific Regional Env...,7; 8; 9; other includes disposable diaper (5.5...
4,EAS,ASM,American Samoa,UMC,composition_paper_cardboard_percent,%,2011.0,SPREP (Secretariat of the Pacific Regional Env...,NaN

In [7]:
df = pd.DataFrame(data)

In [11]:
df.head()

,iso3c,region_id,country_name,income_id,gdp,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,...,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent,waste_treatment_waterways_marine_percent,where_where_is_this_data_measured
0,ABW,LCN,Aruba,HIC,35563.312500,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,11.0,NaN,89.0,NaN,NaN
1,AFG,SAS,Afghanistan,LIC,2057.062256,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other
2,AGO,SSF,Angola,LMC,8036.690430,51.8,6.7,4.4,11.50,11.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ALB,ECS,Albania,UMC,13724.058594,51.4,4.5,4.8,15.21,9.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Some disposal sites
4,AND,ECS,Andorra,HIC,43711.800781,31.2,8.2,2.6,11.60,35.1,...,NaN,52.1,NaN,NaN,NaN,NaN,NaN,47.9,NaN,NaN

In [19]:
words_to_remove = ['treatment', 'collection']
filtered_columns = df.filter(regex=f'.*{words_to_remove}.*', axis=1)
df_filtered = df.drop(columns=filtered_columns.columns)

In [20]:
df_filtered.head()

,iso3c,region_id,country_name,income_id,gdp,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,...,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent,waste_treatment_waterways_marine_percent,where_where_is_this_data_measured
0,ABW,LCN,Aruba,HIC,35563.312500,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,11.0,NaN,89.0,NaN,NaN
1,AFG,SAS,Afghanistan,LIC,2057.062256,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other
2,AGO,SSF,Angola,LMC,8036.690430,51.8,6.7,4.4,11.50,11.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ALB,ECS,Albania,UMC,13724.058594,51.4,4.5,4.8,15.21,9.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Some disposal sites
4,AND,ECS,Andorra,HIC,43711.800781,31.2,8.2,2.6,11.60,35.1,...,NaN,52.1,NaN,NaN,NaN,NaN,NaN,47.9,NaN,NaN

In [25]:
selected_columns_df = df_filtered[['iso3c', 'region_id', 'country_name', 'income_id', 'gdp', 'population_population_number_of_people', 'total_msw_total_msw_generated_tons_year']]